stages: [build, test, release]

#include:
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/build:prepare@$CI_COMMIT_SHA
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/build:extension:backend@$CI_COMMIT_SHA
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/build:extension:frontend@$CI_COMMIT_SHA
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/build:site:backend@$CI_COMMIT_SHA
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/build:site:test:backend@$CI_COMMIT_SHA

include:
  - component: ${CI_SERVER_HOST}/devops/ci-cd-components/release-tools/semantic-release@1.0.3
    inputs:
      stage: release

#create-release:
#  stage: release
#  image: registry.moselwal.io/devops/release-cli/release-cli:latest
#  rules:
#    - if: $CI_COMMIT_TAG
#  script: echo "Creating release $CI_COMMIT_TAG"
#  release:
#    tag_name: $CI_COMMIT_TAG
#    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
