stages: [build, test, release]

include:
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:commit-msg@$CI_COMMIT_SHA
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:normalize@$CI_COMMIT_SHA
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:psr-verify@$CI_COMMIT_SHA
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:validate@$CI_COMMIT_SHA
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:eslint@$CI_COMMIT_SHA


create-release:
  stage: release
  image: registry.moselwal.io/devops/release-cli/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script: echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
